name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true  
        tags: myapp:latest
    
    - name: Verify Docker image
      run: |
        # List Docker images to verify it was built
        docker images
        
        # You can run a container from the image if needed
        docker run --rm myapp:latest echo "Image works!"